### ISSUE TITLE
Errors are not handled correctly with elasticsearch 2.0.0

### ISSUE THREAD

**Issue by Lisio** [yiisoft/yii2-elasticsearch#36] opened 2015-11-08 13:19 UTC
decodeErrorBody method of Connection class tries to edit error message as a string, but in 2.0.0 it is an associative array.

**Comment by samdark** [comment] 2015-11-10 17:26
@Lisio any idea on how to fix that?

**Comment by Lisio** [comment] 2015-11-10 17:35
Not sure, maybe just replace
```php
    protected function decodeErrorBody($body)
    {
        try {
            $decoded = Json::decode($body);
            if (isset($decoded['error'])) {
                $decoded['error'] = preg_replace('/\b\w+?Exception\[/', "<span style=\"color: red;\">\\0</span>\n               ", $decoded['error']);
            }
            return $decoded;
        } catch(InvalidParamException $e) {
            return $body;
        }
    }
```

with

```php
    protected function decodeErrorBody($body)
    {
        try {
            $decoded = Json::decode($body);
            if (isset($decoded['error']) && is_string($decoded['error'])) {
                $decoded['error'] = preg_replace('/\b\w+?Exception\[/', "<span style=\"color: red;\">\\0</span>\n               ", $decoded['error']);
            }
            return $decoded;
        } catch(InvalidParamException $e) {
            return $body;
        }
    }
```

**Comment by cebe** [comment] 2016-02-25 20:28
duplicate of #65

**Closed by cebe** 2016-02-25 20:28 UTC
Labels: bug
