### ISSUE TITLE
Elastics 2.1.0 - php note: Array to string conversion Connection.php#L492

### ISSUE THREAD

**Issue by zinzinday** [yiisoft/yii2-elasticsearch#45] opened 2015-12-13 00:40 UTC
I have query search 
http://prntscr.com/9dhon1

https://github.com/yiisoft/yii2-elasticsearch/blob/master/Connection.php#L492

http://prntscr.com/9dhp5r
$decoded['error'] type array not an string
http://prntscr.com/9dhr66

**Comment by cebe** [comment] 2015-12-13 01:41
duplicate of #36 ?

**Closed** 2016-02-25 20:28 UTC
