### ISSUE TITLE
error field is an array, but treated like a string

### ISSUE THREAD

**Issue by Zenexer** [yiisoft/yii2-elasticsearch#65] opened 2016-01-27 11:37 UTC
In Connection.php around line 442:

``` php
$decoded['error'] = preg_replace('/\b\w+?Exception\[/', "<span style=\"color: red;\">\\0</span>\n               ", $decoded['error']);
```

However, $decoded['error'] looks like this:

``` php
array (
  'root_cause' =>
  array (
    0 =>
    array (
      'type' => 'merge_mapping_exception',
      'reason' => 'Merge failed with failures ...',
    ),
  ),
  'type' => 'merge_mapping_exception',
  'reason' => 'Merge failed with failures ...',
)
```

Elasticsearch 2.x, PHP 5.6, yii2-elasticsearch 2.0.3, yii2 2.0.6

**Comment by samdark** [comment] 2016-01-27 12:32
How to reproduce it?

**Comment by cebe** [comment] 2016-01-27 12:35
see #23

**Comment by Zenexer** [comment] 2016-01-27 12:43
@samdark Cause Elasticsearch to produce an error response.

@cebe Yes, that seems to be the same problem.  Looks like the pull request hasn't received much attention, though.

**Comment by cebe** [comment] 2016-01-27 12:51
yeah sorry. I'm busy with a lot of other things. Will be in the next release.

**Comment by michaelarnauts** [comment] 2016-02-22 15:41
Any idea when we could expect this in a release? We have this issue since we've upgraded to Elasticsearch 2.x

**Comment by cebe** [comment] 2016-02-25 20:22
this is fixed, planning to make a release in a few weeks.

**Closed** 2016-02-25 20:22 UTC
Labels: bug
