### ISSUE TITLE
Relation don't work if you use "asArray()"

### ISSUE THREAD

**Issue by shcherbanich** [yiisoft/yii2-elasticsearch#21] opened 2015-07-15 19:55 UTC
My elasticsearch model:

```
class User extends \yii\elasticsearch\ActiveRecord {

    public function attributes()
    {
        return ['id', 'name', 'address', 'id_company'];
    }

    public function getCompany()
    {
        return $this->hasOne(Company::className(), ['id' => 'id_company']);
    }
}
```

Problem:

```
$models = User::find()->where(['id'=>1])->with('company')->one();

// $models->company !== null;

$models = User::find()->where(['id'=>1])->with('company')->asArray()->one();

// isset($models['company']) === false;
```

😖

**Comment by cebe** [comment] 2016-02-25 20:54
yes, this is currently not implemented for asArray.

**Comment by beowulfenator** [comment] 2020-05-28 21:42
Essentially duplicate of #18. Relations are lazy-loaded, and asArray() does not follow them.

**Closed by beowulfenator** 2020-05-28 21:42 UTC
Labels: type:bug

**Comment by beowulfenator** [comment] 2020-05-28 21:54
In other words, relations work, `with()` is not implemented
